<?php

namespace Phramework\API\models;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-13 at 15:46:52.
 */
class utilTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var util
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new util;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Phramework\API\models\util::url
     * @todo   Implement testUrl().
     */
    public function testUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\models\util::url_interface
     * @todo   Implement testUrl_interface().
     */
    public function testUrl_interface() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\models\util::to_ascii
     * @todo   Implement testTo_ascii().
     */
    public function testTo_ascii() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\models\util::begins_with
     * @todo   Implement testBegins_with().
     */
    public function testBegins_with() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\models\util::_date_formatted
     * @todo   Implement test_date_formatted().
     */
    public function test_date_formatted() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\models\util::date_formatted
     * @todo   Implement testDate_formatted().
     */
    public function testDate_formatted() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\models\util::user_content
     * @todo   Implement testUser_content().
     */
    public function testUser_content() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\models\util::token
     * @todo   Implement testToken().
     */
    public function testToken() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\models\util::is_ajax_request
     * @todo   Implement testIs_ajax_request().
     */
    public function testIs_ajax_request() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\models\util::is_HTTPS
     * @todo   Implement testIs_HTTPS().
     */
    public function testIs_HTTPS() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\models\util::get_ipaddress
     * @todo   Implement testGet_ipaddress().
     */
    public function testGet_ipaddress() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\models\util::cache_headers
     * @todo   Implement testCache_headers().
     */
    public function testCache_headers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\models\util::check_include_root
     * @todo   Implement testCheck_include_root().
     */
    public function testCheck_include_root() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\models\util::merge_put_paramters
     * @todo   Implement testMerge_put_paramters().
     */
    public function testMerge_put_paramters() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\models\util::directory_to_array
     * @todo   Implement testDirectory_to_array().
     */
    public function testDirectory_to_array() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\models\util::delete_directory_contents
     * @todo   Implement testDelete_directory_contents().
     */
    public function testDelete_directory_contents() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\models\util::headers
     * @todo   Implement testHeaders().
     */
    public function testHeaders() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\models\util::readable_random_string
     * @todo   Implement testReadable_random_string().
     */
    public function testReadable_random_string() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\models\util::curl_headers
     * @todo   Implement testCurl_headers().
     */
    public function testCurl_headers() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\models\util::curl_download
     * @todo   Implement testCurl_download().
     */
    public function testCurl_download() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\models\util::tempfile
     * @todo   Implement testTempfile().
     */
    public function testTempfile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\models\util::extension
     * @todo   Implement testExtension().
     */
    public function testExtension() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\models\util::get_path
     * @todo   Implement testGet_path().
     */
    public function testGet_path() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\models\util::to_single_slashes
     * @todo   Implement testTo_single_slashes().
     */
    public function testTo_single_slashes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\models\util::parse_regexp
     * @todo   Implement testParse_regexp().
     */
    public function testParse_regexp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\models\util::get_file_size
     * @todo   Implement testGet_file_size().
     */
    public function testGet_file_size() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
