<?php

namespace Phramework\Validate;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-10-05 at 22:11:07.
 */
class EnumTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Enum
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Enum(['1', '2', 'ok', 5], true);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    public function validateSuccessProvider()
    {
        //input, expected
        return [
            ['1', '1'],
            ['2', '2'],
            ['ok', 'ok'],
            [5, 5]
        ];
    }

    public function validateFailureProvider()
    {
        //input
        return [
            [1],
            [2],
            ['5'],
            [4],
            ['7'],
            ['string']
        ];
    }

    /**
     * @dataProvider validateSuccessProvider
     * @covers Phramework\Validate\Enum::validate
     */
    public function testValidateSuccess($input, $expected)
    {
        $return = $this->object->validate($input);

        $this->assertTrue($return->status);
        $this->assertSame($expected, $return->value);
    }

    /**
     * @dataProvider validateFailureProvider
     * @covers Phramework\Validate\Enum::validate
     */
    public function testValidateFailure($input)
    {
        $return = $this->object->validate($input);

        $this->assertFalse($return->status);
    }

    /**
     * @covers Phramework\Validate\Enum::getType
     */
    public function testGetType()
    {
        $this->assertEquals('enum', $this->object->getType());
    }
}
