<?php

namespace Phramework\URIStrategy;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-18 at 02:24:38.
 */
class ClassBasedTest extends \PHPUnit\Framework\TestCase
{

    /**
     * @var ClassBased
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp():void
    {
        $this->object = new ClassBased([], [], []);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown():void
    {
        $this->markTestIncomplete();
    }

    /**
     * @covers Phramework\URIStrategy\ClassBased::invoke
     * @todo   Implement testInvoke().
     */
    public function testInvoke()
    {
        $this->markTestIncomplete();
    }
}
