<?php

namespace Phramework\Models;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-18 at 14:44:33.
 */
class FilterTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Filter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Filter;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Phramework\Models\Filter::in
     * @todo   Implement testIn().
     */
    public function testIn()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\Models\Filter::inEntry
     * @todo   Implement testInEntry().
     */
    public function testInEntry()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\Models\Filter::out
     * @todo   Implement testOut().
     */
    public function testOut()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\Models\Filter::outEntry
     * @todo   Implement testOutEntry().
     */
    public function testOutEntry()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\Models\Filter::string
     * @todo   Implement testString().
     */
    public function testString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\Models\Filter::email
     * @todo   Implement testEmail().
     */
    public function testEmail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\Models\Filter::boolean
     * @todo   Implement testBoolean().
     */
    public function testBoolean()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\Models\Filter::typecast
     * @todo   Implement testTypecast().
     */
    public function testTypecast()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\Models\Filter::castEntry
     * @todo   Implement testCastEntry().
     */
    public function testCastEntry()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\Models\Filter::cast
     * @todo   Implement testCast().
     */
    public function testCast()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}
