<?php

namespace Phramework\API;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-04-13 at 15:33:37.
 */
class APITest extends \PHPUnit_Framework_TestCase {

    /**
     * @var API
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $settings = [
            'language' => 'en'
        ];
        $this->object = new API($settings, ['test'], ['test'], ['test']);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Phramework\API\API::set_authentication_class
     * @todo   Implement testSet_authentication_class().
     */
    public function testSet_authentication_class() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\API::authenticate
     * @todo   Implement testAuthenticate().
     */
    public function testAuthenticate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\API::invoke
     * @todo   Implement testInvoke().
     */
    public function testInvoke() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\API::get_user
     * @todo   Implement testGet_user().
     */
    public function testGet_user() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\API::get_timezone_offset
     * @todo   Implement testGet_timezone_offset().
     */
    public function testGet_timezone_offset() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\API::get_language
     * @todo   Implement testGet_language().
     */
    public function testGet_language() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\API::get_method
     * @todo   Implement testGet_method().
     */
    public function testGet_method() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\API::get_controller
     * @todo   Implement testGet_controller().
     */
    public function testGet_controller() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\API::get_mode
     * @todo   Implement testGet_mode().
     */
    public function testGet_mode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\API::get_setting
     * @todo   Implement testGet_setting().
     */
    public function testGet_setting() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\API::view
     * @todo   Implement testView().
     */
    public function testView() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\API::clude
     * @todo   Implement testClude().
     */
    public function testClude() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\API::write_error_log
     * @todo   Implement testWrite_error_log().
     */
    public function testWrite_error_log() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\API\API::add_step_callback
     * @todo   Implement testAdd_step_callback().
     */
    public function testAdd_step_callback() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

}
