<?php

namespace Phramework\Models;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-18 at 14:44:28.
 */
class RequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Request
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Request;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
        
    }

    /**
     * @covers Phramework\Models\Request::checkPermission
     * @todo   Implement testCheckPermission().
     */
    public function testCheckPermission()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\Models\Request::requireParameters
     * @todo   Implement testRequireParameters().
     */
    public function testRequireParameters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\Models\Request::resourceId
     * @todo   Implement testResourceId().
     */
    public function testResourceId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\Models\Request::requireId
     * @todo   Implement testRequireId().
     */
    public function testRequireId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\Models\Request::parseModel
     * @todo   Implement testParseModel().
     */
    public function testParseModel()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\Models\Request::headers
     * @todo   Implement testHeaders().
     */
    public function testHeaders()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Phramework\Models\Request::mergePutParamters
     * @todo   Implement testMergePutParamters().
     */
    public function testMergePutParamters()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
